#pragma once
#include <wx/defs.h>

enum MainFrameIDs {
    DIR_PICKER = wxID_LAST + 1,
    RUN_BUTTON,
    FOLDER_LOCATION,
    GRAPH_PICKER,
    LOAD_BUTTON,
    GRAPH_LOCATION
};

enum FaceClusterWindowIDs {
    PREV_IMG = wxID_LAST + 1,
    NEXT_IMG,
    OPEN_IMG_LOC,
    PREV_CLUSTER,
    NEXT_CLUSTER
};

enum ProgressWindowIDs {
    DETECTING_IMAGE_TXT = wxID_LAST + 1,
    DETECTING_FACE_TXT,
    DETECTING_FACE_GAUGE, 
    COMPARING_FACE_TXT,
    COMPARING_FACE_GAUGE,
    CLUSTERING_FACE_TXT
};

enum EventsIDs {
    CREATE_PROGRESS_WINDOW = wxID_LAST + 1,
    CREATE_FACE_CLUSTER_WINDOW,
    DETECTED_IMAGE, 
    DONE_DETECTING_IMAGES,
    DETECTED_FACE,
    DONE_DETECTING_FACES_ON_IMAGE,
    DONE_DETECTING_FACES,
    NN_DONE,
    COMPARED_FACE,
    DONE_COMPARING_FACES,
    DONE_CLUSTERING_FACES
};